title: Zixiao Wang's Homepage
page-top-title: Zixiao Wang
top-section-bg-text: Architectural Technology and Science
home-subtitle: Zixiao Wang&ensp;|&ensp;王子骁
copyright-text: '&copy; Zixiao Wang 2025. All Rights Reserved.'
